BEGIN;

INSERT INTO lands (park_id, name) VALUES
	(2, 'A Bug’s Lnd'),
	(2, 'Buena Vista Stret'),
	(2, 'Car’s Lnd'),
	(2, 'Grizzly Pak'),
	(2, 'Hollywood Lnd'),
	(2, 'Pacific Whrf'),
	(2, 'Paradise Per'),
	(1, 'Adventurelnd'),
	(1, 'Critter Counry'),
	(1, 'Fantasylnd'),
	(1, 'Frontierlnd'),
	(1, 'Main Street, U..A'),
	(1, 'Mickey’s Toon Twn'),
	(1, 'New Orleans Squre'),
	(1, 'Tomorrowlnd'),
	(3, 'DD');

INSERT INTO attractions (park_id, land_id, name) VALUES
	(2, 1, 'Flik''s Flyers'),
	(2, 1, 'Francis'' Ladybug Boogie'),
	(2, 1, 'Heimlich''s Chew Chew Train'),
	(2, 1, 'It''s Tough to be a Bug!'),
	(2, 1, 'Princess Dot Puddle Park'),
	(2, 1, 'Tuck and Roll''s Drive ''Em Buggies'),
	(2, 2, 'Red Car Trolley'),
	(2, 3, 'Luigi''s Rollickin’ Roadsters'),
	(2, 3, 'Mater''s Junkyard Jamboree'),
	(2, 3, 'Radiator Springs Racers'),
	(2, 4, 'Grizzly River Run'),
	(2, 4, 'Redwood Creek Challenge Trail'),
	(2, 4, 'Soarin'' Around the World'),
	(2, 5, 'Animation Academy'),
	(2, 5, 'Guardians of the Galaxy - Mission BREAKOUT!'),
	(2, 5, 'Hyperion Theater'),
	(2, 5, 'Monsters, Inc. Mike and Sulley to the Rescue!'),
	(2, 5, 'Sorcerer''s Workshop'),
	(2, 5, 'Turtle Talk with Crush'),
	(2, 6, 'The Bakery Tour'),
	(2, 7, 'California Screamin’'),
	(2, 7, 'Games of the Boardwalk'),
	(2, 7, 'Golden Zephr'),
	(2, 7, 'Goofy''s Sky School'),
	(2, 7, 'Jumpin'' Jellyfish'),
	(2, 7, 'King Triton’s Carousel'),
	(2, 7, 'The Little Mermaid ~ Ariel''s Undersea Adventure'),
	(2, 7, 'Mickey''s Fun Wheel'),
	(2, 7, 'Silly Symphony Swings'),
	(2, 7, 'Toy Story Midway Mania!'),
	(1, 8, 'Enchanted Tiki Room'),
	(1, 8, 'Indiana Jones™ Adventure'),
	(1, 8, 'Jungle Cruise'),
	(1, 8, 'Tarzan''s Treehouse™'),
	(1, 9, 'The Many Adventures of Winnie the Pooh'),
	(1, 9, 'Splash Mountain'),
	(1, 10, 'Alice in Wonderland'),
	(1, 10, 'Casey Jr. Circus Train'),
	(1, 10, 'Dumbo the Flying Elephant'),
	(1, 10, 'It''s a Small World'),
	(1, 10, 'King Arthur Carrousel'),
	(1, 10, 'Mad Tea Party'),
	(1, 10, 'Matterhorn Bobsleds'),
	(1, 10, 'Mr. Toads Wild Ride'),
	(1, 10, 'Peter Pan’s Flight'),
	(1, 10, 'Pinocchio''s Daring Journey'),
	(1, 10, 'Sleeping Beauty Castle'),
	(1, 10, 'Snow White''s Scary Adventure'),
	(1, 10, 'Storybook Land Canal Boats'),
	(1, 11, 'Big Thunder Mountain Railroad'),
	(1, 11, 'Frontierland Shootin'' Exposition'),
	(1, 11, 'Mark Twain Riverboat'),
	(1, 11, 'Pirate''s Lair on Tom Sawyer Island'),
	(1, 12, 'The Disney Gallery'),
	(1, 12, 'Disneyland Railroad'),
	(1, 12, 'Great Moments with Mr. Lincoln'),
	(1, 12, 'Main Street Cinema'),
	(1, 12, 'Main Street Vehicles'),
	(1, 13, 'Chip ''n Dale Treehouse'),
	(1, 13, 'Donald''s Boat'),
	(1, 13, 'Gadget''s Go Coaster'),
	(1, 13, 'Goofy''s Playhouse'),
	(1, 13, 'Mickey''s House'),
	(1, 13, 'Minnie''s House'),
	(1, 13, 'Roger Rabbit''s Car Toon Spin'),
	(1, 14, 'Haunted Mansion'),
	(1, 14, 'Pirates of the Carribbean'),
	(1, 15, 'Astro Orbitor'),
	(1, 15, 'Autopia'),
	(1, 15, 'Buzz Lightyear Astro Blasters'),
	(1, 15, 'Disneyland Monorail'),
	(1, 15, 'Finding Nemo Submarine Voyage'),
	(1, 15, 'Space Mountain'),
	(1, 15, 'Star Tours - The Adventure Continues'),
	(1, 15, 'Star Wars Launch Bay'),
	(1, 15, 'Star Wars: Path of the Jedi');	

COMMIT;